import { StyleSheet, Platform } from "react-native";
import { Colors } from "@/theme/colors";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#fff",
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  container: {
    flexGrow: 1,
    alignItems: "center",
    backgroundColor: "#fff",
    paddingTop: 24,
    paddingHorizontal: 16,
  },
  containerDesktop: {
    paddingTop: 60,
  },
  content: {
    width: "100%",
    maxWidth: 480,
  },
  section: {
    backgroundColor: "#fff",
    padding: 16,
    alignItems: "center",
  },
  iconContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: Colors.surfaceAlt,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
  },
  iconContainerSubscribed: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: `${Colors.purple}15`,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 28,
  },
  iconInnerGlow: {
    position: "absolute",
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: `${Colors.purple}20`,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: Colors.text,
    textAlign: "center",
    marginBottom: 12,
  },
  titleSubscribed: {
    fontSize: 30,
    fontWeight: "700",
    color: Colors.text,
    textAlign: "center",
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 16,
    color: Colors.textLightDark,
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 24,
  },
  subtitleSubscribed: {
    fontSize: 16,
    color: Colors.textLightDark,
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 28,
  },
  emailHighlight: {
    fontWeight: "600",
    color: Colors.purple,
  },
  benefitsList: {
    width: "100%",
    gap: 16,
    marginBottom: 24,
  },
  benefitItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  benefitText: {
    fontSize: 15,
    color: Colors.textLightDark,
  },
  benefitsCard: {
    width: "100%",
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 16,
    padding: 20,
    gap: 16,
  },
  benefitsCardTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  benefitItemSubscribed: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  benefitIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.purple,
    justifyContent: "center",
    alignItems: "center",
  },
  benefitTextSubscribed: {
    fontSize: 15,
    color: Colors.text,
    fontWeight: "500",
    flex: 1,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 52,
    width: "100%",
    marginBottom: 16,
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: Colors.text,
    ...Platform.select({
      web: {
        outlineStyle: "none",
      },
    }),
  },
  loggedInEmail: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 52,
    width: "100%",
    gap: 12,
    marginBottom: 16,
  },
  loggedInEmailText: {
    fontSize: 16,
    color: Colors.text,
    fontWeight: "500",
  },
  subscribeButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.purple,
    borderRadius: 12,
    height: 52,
    width: "100%",
    ...Platform.select({
      web: {
        cursor: "pointer",
        transition: "transform 0.1s, background-color 0.2s",
      },
    }),
  },
  subscribeButtonPressed: {
    backgroundColor: Colors.purpleDark,
    transform: [{ scale: 0.98 }],
  },
  subscribeButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  privacyNote: {
    fontSize: 13,
    color: Colors.textMuted,
    textAlign: "center",
    marginTop: 16,
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: Colors.surfaceAlt,
    marginVertical: 24,
  },
  unsubscribeLabel: {
    fontSize: 14,
    color: Colors.textMuted,
    marginBottom: 12,
  },
  unsubscribeButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.textMuted,
  },
  unsubscribeButtonText: {
    fontSize: 14,
    color: Colors.textMuted,
  },
});
